name: Publish [kmp-realm] to Maven Central

permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  build-release:
    uses: ./.github/workflows/buildRelease.yml
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  publish:
    needs: build-release

    env:
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      OSSRH_STAGING_PROFILE_ID: ${{ secrets.OSSRH_STAGING_PROFILE_ID }}

    strategy:
      matrix:
        include:
          - target: :kmp-realm:publishIosArm64PublicationToSonatypeRepository
            os: macos-latest
          - target: :kmp-realm:publishIosSimulatorArm64PublicationToSonatypeRepository
            os: macos-latest
          - target: :kmp-realm:publishIosX64PublicationToSonatypeRepository
            os: macos-latest
          - target: :kmp-realm:publishAndroidReleasePublicationToSonatypeRepository
            os: ubuntu-latest
          - target: :kmp-realm:publishKotlinMultiplatformPublicationToSonatypeRepository
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Set up Java JDK ${{ vars.JAVA_JDK_VERSION }}"
        uses: actions/setup-java@v4
        with:
          java-version: '${{ vars.JAVA_JDK_VERSION }}'
          distribution: "zulu"

      - name: Setup Gradle cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.konan
          key: ${{ runner.os }}-${{ hashFiles('**/.lock') }}

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          passphrase: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}

      - name: Gradle publish
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: |
            ${{ matrix.target }}
            closeAndReleaseSonatypeStagingRepository
            -Psigning.gnupg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
            -Psigning.gnupg.keyName=${{ secrets.OSSRH_GPG_SECRET_KEY_ID }}
            -PsonatypeUsername=${{ secrets.OSSRH_USERNAME }}
            -PsonatypePassword=${{ secrets.OSSRH_PASSWORD }}
            -PsonatypeStagingProfileId=${{ secrets.OSSRH_STAGING_PROFILE_ID }}
